name: Update dependencies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: |
          git config --global user.name "Kálmán Neszlényi"
          git config --global user.email "73647069+kamka427@users.noreply.github.com"
      - run: |
          echo '@daniel-bali:registry=https://npm.pkg.github.com' > .npmrc
          echo 'always-auth=true' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.MY_PAT }}' >> .npmrc
      - run: |
          npm i
          npm i @kamka427/bene-ws-package
      - run: |
          git add .
          git commit -m "Update dependencies"
          git push